### PR TITLE
replace fuzzywuzzy

### PR DESCRIPTION
**Pull request by ghost**
FuzzyWuzzy is GPL Licensed, which is incompatible with the license used by this project. This Pull Request replaces FuzzyWuzzy with [RapidFuzz](https://github.com/maxbachmann/rapidfuzz), which implements the same algorithms. It is licensed in a compatible way (MIT License) and is faster than FuzzyWuzzy.

### CODE REVIEW

**Comment by domcross** [comment]
Thanks for the PR. I am aware of the licensing issue, but this is not a official Mycroft skill (marketplace). 
Unfortunately latest Rapidfuzz release can not be build on Mark-I (Still running on Debian Jessie), therefor I will not merge this PR until there is a solution for this.

**Comment by ghost** [comment]
I did just try to install it in a Debian Jessie docker container (gcc 4.9.2 and Python 3.4) which worked fine. What's the error when you try to install it on the Mark-I?

**Comment by domcross** [comment]
I tried rapidfuzz 0.11.3 last week and it failed with a mile-long error message from GCC.
Seems like there has been some update activity for rapidfuzz since then - version 0.12.2 installs fine.
Will perform some tests, then PR can be merged...

**Comment by ghost** [comment]
True I just tried with 0.11.3 and it failed as well. Apparently it used some features in the templates that were not supported by gcc back then. C++ error messages related to templates get really long. Gave me a 7k line long error message ...

**Review by domcross — APPROVED** [review]
looks good to me

**Pull request merged**
